services:
  openjdk:
    container_name: spring
    image: openjdk/personal
    build: ./openjdk
    restart: always
    networks:
      - backend #spring solo puede hablar en la red interna, no muestra nada hacia afuera
  proxy_inverso:
    container_name: proxy
    image: nginx:latest
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/cert1.pem:/etc/nginx/cert/localhost.pem
      - ./nginx/cert/privkey1.pem:/etc/nginx/cert/localhost.key
    restart: always
    networks:
      - frontend  #en frontend publica sus puertos hacia afuera
      - backend # a traves de backend puede hablar con spring
    ports:
      - "80:80"
      - "443:443"
    links:
     - openjdk

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'e2t_2024'
      MYSQL_DATABASE: 'e2t_mysql'
      MYSQL_USER: 'e2t_user'
      MYSQL_PASSWORD: 'e2t_2024'
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  backend:
    name: backend
    internal: true
  frontend:
    name: frontend
    driver: bridge